# Generated by Django 4.0.4 on 2022-04-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimages',
            old_name='carousel_img',
            new_name='image',
        ),
    ]
