# Generated by Django 4.0.4 on 2022-04-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0002_alter_productcategory_category_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsinglecategory',
            old_name='category_name',
            new_name='product_category_model',
        ),
    ]
