# Generated by Django 4.0.4 on 2022-04-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0002_agent_logo_userprofile_remove_carouselimages_posts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=998)),
                ('logo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Header',
            },
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
