# Generated by Django 4.0.4 on 2022-04-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0002_rename_carousel_img_carouselimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimages',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aviato.post'),
        ),
    ]
