# Generated by Django 4.0.4 on 2022-04-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0003_alter_carouselimages_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimages',
            old_name='image',
            new_name='carousel_img_1',
        ),
        migrations.RemoveField(
            model_name='carouselimages',
            name='posts',
        ),
        migrations.AddField(
            model_name='carouselimages',
            name='carousel_img_2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselimages',
            name='carousel_img_3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
