# Generated by Django 4.0.4 on 2022-04-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0003_rename_category_name_productsinglecategory_product_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trendy_products_type', models.CharField(max_length=200)),
                ('trendy_products_cost', models.IntegerField(default=30)),
                ('trendy_products_sale', models.CharField(blank=True, max_length=80)),
                ('trendy_products_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Trendy Products',
                'verbose_name_plural': 'Trendy Products',
            },
        ),
    ]
