# Generated by Django 4.0.4 on 2022-04-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0004_rename_text_carouselimages_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimages',
            name='menu',
            field=models.CharField(max_length=200),
        ),
    ]
