# Generated by Django 4.0.4 on 2022-04-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0004_trendyproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyproducts',
            name='category_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aviato.productsinglecategory'),
        ),
    ]
