# Generated by Django 4.0.4 on 2022-04-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0005_rename_carousel_img_1_carouselimages_carousel_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo ',
            },
        ),
    ]
