# Generated by Django 4.0.4 on 2022-04-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0005_alter_carouselimages_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimages',
            name='menu',
            field=models.TextField(max_length=200),
        ),
    ]
