# Generated by Django 4.0.4 on 2022-04-30 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0006_alter_productcategory_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendyproducts',
            name='category_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviato.productsinglecategory'),
        ),
    ]
