# Generated by Django 4.0.4 on 2022-04-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0006_alter_carouselimages_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimages',
            name='button',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
