# Generated by Django 4.0.4 on 2022-04-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0007_alter_trendyproducts_category_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendyproducts',
            name='category_model',
        ),
    ]
