# Generated by Django 4.0.4 on 2022-04-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0007_carouselimages_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_paragraph', models.CharField(max_length=200)),
                ('product_category_box_head', models.CharField(max_length=150)),
                ('product_category_box_text', models.CharField(max_length=200)),
                ('product_category_box_carousel', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Category',
            },
        ),
    ]
