# Generated by Django 4.0.4 on 2022-04-30 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0011_alter_productcategory_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='organiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aviato.userprofile'),
            preserve_default=False,
        ),
    ]
