# Generated by Django 4.0.4 on 2022-04-30 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0012_productcategory_organiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyproducts',
            name='category_model',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='aviato.productsinglecategory'),
            preserve_default=False,
        ),
    ]
