# Generated by Django 4.0.4 on 2022-04-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0015_alter_productcategory_category_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_category_box_carousel',
            new_name='product_category_box_carousel_1',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_category_box_carousel_2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_category_box_carousel_3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
