# Generated by Django 4.0.4 on 2022-04-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0016_rename_product_category_box_carousel_productcategory_product_category_box_carousel_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_category_box_carousel_1',
            new_name='product_category_box_carousel',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='product_category_box_carousel_2',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='product_category_box_carousel_3',
        ),
    ]
