# Generated by Django 4.0.4 on 2022-04-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0017_rename_product_category_box_carousel_1_productcategory_product_category_box_carousel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='aviato.productsinglecategory'),
        ),
    ]
