# Generated by Django 4.0.4 on 2022-04-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0019_productcategory_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendyproducts',
            name='category_model',
        ),
    ]
