# Generated by Django 4.0.4 on 2022-04-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0020_remove_trendyproducts_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trendy_products_category', models.CharField(max_length=100)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviato.userprofile')),
            ],
            options={
                'verbose_name': 'Trendy Category',
                'verbose_name_plural': 'Trendy Category',
            },
        ),
        migrations.AddField(
            model_name='trendyproducts',
            name='trendy_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aviato.trendyproductscategory'),
        ),
    ]
