# Generated by Django 4.0.4 on 2022-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0021_trendyproductscategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeNewpaperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_newspaper_header', models.CharField(blank=True, max_length=200)),
                ('subscribe_newspaper_text', models.TextField(blank=True, max_length=350)),
            ],
            options={
                'verbose_name': 'Subscribe Newspaper',
                'verbose_name_plural': 'Subscribe Newspaper',
            },
        ),
    ]
