# Generated by Django 4.0.4 on 2022-05-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0022_subscribenewpapermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSocialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isntagram_header', models.CharField(blank=True, max_length=200)),
                ('instagram_view_image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Instagram View',
                'verbose_name_plural': 'Instagram View',
            },
        ),
    ]
