# Generated by Django 4.0.4 on 2022-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0023_instagramsocialmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramsocialmodel',
            old_name='instagram_view_image',
            new_name='instagram_view_image_1',
        ),
        migrations.AddField(
            model_name='instagramsocialmodel',
            name='instagram_view_image_2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='instagramsocialmodel',
            name='instagram_view_image_3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
