# Generated by Django 4.0.4 on 2022-05-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0025_instagramsocialmodel_instagram_view_image_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsocialmodel',
            name='instagram_view_image_5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='instagramsocialmodel',
            name='instagram_view_image_6',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='instagramsocialmodel',
            name='instagram_view_image_7',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
