# Generated by Django 4.0.4 on 2022-05-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0026_instagramsocialmodel_instagram_view_image_5_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramsocialmodel',
            old_name='instagram_view_image_1',
            new_name='instagram_view_image',
        ),
        migrations.RemoveField(
            model_name='instagramsocialmodel',
            name='instagram_view_image_2',
        ),
        migrations.RemoveField(
            model_name='instagramsocialmodel',
            name='instagram_view_image_3',
        ),
        migrations.RemoveField(
            model_name='instagramsocialmodel',
            name='instagram_view_image_4',
        ),
        migrations.RemoveField(
            model_name='instagramsocialmodel',
            name='instagram_view_image_5',
        ),
        migrations.RemoveField(
            model_name='instagramsocialmodel',
            name='instagram_view_image_6',
        ),
        migrations.RemoveField(
            model_name='instagramsocialmodel',
            name='instagram_view_image_7',
        ),
        migrations.RemoveField(
            model_name='instagramsocialmodel',
            name='isntagram_header',
        ),
    ]
