# Generated by Django 4.0.4 on 2022-05-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0028_instagramsocialmodel_organiser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_copyright', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Footer',
            },
        ),
    ]
